spring.application.name=Task-Manager
spring.datasource.url=jdbc:mysql://localhost:3306/task_manager
spring.datasource.username=ameth
spring.datasource.password=Sword@rtonl1ne
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
